name: Build Frontend

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          yarn install

      - name: Prepare frontend
        run: |
          cd frontend
          yarn frontend:prep

      - name: Commit and Push Changes
        if: ${{ !env.ACT }}  # Only run if NOT running with act
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update index.html after frontend:prep"

            max_retries=5
            retry_count=0

            while [ $retry_count -lt $max_retries ]; do
              echo "Attempting to push (attempt $((retry_count + 1))/$max_retries)..."

              if git push; then
                echo "Push successful!"
                break
              else
                echo "Push failed, rebasing and retrying..."
                retry_count=$((retry_count + 1))

                if [ $retry_count -lt $max_retries ]; then
                  git pull --rebase origin ${{ github.ref_name }}
                  sleep $((RANDOM % 10 + 1))
                else
                  echo "Max retries reached, push failed"
                  exit 1
                fi
              fi
            done

            echo "Changes committed and pushed successfully"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}