name: openai-news-aggregator
on:
  schedule:
    - cron: '0 15 * * *' # Runs at 17 00 Berlin Time
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  openai-news-aggregator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Start with gpt-4o, but you can easily add more models here later
        # e.g., ["gpt-4o", "gpt-4-turbo"]
        model: ["gpt-4o"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call OpenAI Agents and Store Results
        run: |
          # Get current date in YYYY-MM-DD format
          current_date=$(date +%Y-%m-%d)
          # Sanitize model name for directory usage (e.g., gpt-4o -> gpt-4o)
          model_name_sanitized=$(echo "${{ matrix.model }}" | tr -c 'a-zA-Z0-9-' '-')
          
          # Create directory structure
          output_dir="news/${current_date}/${model_name_sanitized}"
          mkdir -p "$output_dir"
          
          echo "Creating output directory: $output_dir"
          
          # Check if model-output.json already exists for this model
          if [ -f "${output_dir}/model-output.json" ]; then
            echo "Output file already exists for ${model_name_sanitized}, skipping..."
            exit 0
          fi
          
          # Step 1: Get news content using the main model
          echo "Step 1: Getting news content with ${{ matrix.model }}..."

          # Read the prompt from a file
          get_json_news_prompt=$(cat "${{ github.workspace }}/.github/prompts/get_json_news.prompt")
          
          # Use jq to build the JSON payload for a single API call.
          # We use `web_search_preview` for real-time data and `response_format` to enforce JSON output.
          payload=$(jq -n \
            --arg model "${{ matrix.model }}" \
            --arg prompt "$get_json_news_prompt" \
            '{
              model: $model,
              input: $prompt,
              tools: [{"type": "web_search_preview"}],
              "text": {
                  "format": {
                    "type": "text"
                  }
              },
              temperature: 0
            }')

          response=$(curl -s "https://api.openai.com/v1/responses" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d "$payload")
          
          echo "Raw API response:"
          echo "$response"

          # Extract the JSON content. Since we requested JSON format, the content should be the JSON object itself.
          generated_content=$(echo "$response" | jq -r '.choices[0].message.content' 2>/dev/null)
          
          # Basic validation that we got some content back
          if [ -z "$generated_content" ] || [ "$generated_content" = "null" ]; then
            echo "Error: Failed to extract content from OpenAI response."
            echo "Full response was:"
            echo "$response" | jq '.'
            exit 1
          fi

          echo "JSON content extracted successfully:"
          echo "$generated_content"
          
          # Save the cleaned JSON content to file
          echo "$generated_content" > "${output_dir}/model-output.json"
          
          echo "Content saved to: ${output_dir}/model-output.json"
          
          # Verify the file was created and show its contents
          if [ -f "${output_dir}/model-output.json" ]; then
            echo "File created successfully. Contents:"
            cat "${output_dir}/model-output.json"
            # Pretty print if it's valid JSON
            echo "Pretty printed JSON:"
            cat "${output_dir}/model-output.json" | jq '.' 2>/dev/null || echo "Content is not valid JSON"
          else
            echo "Error: File was not created"
          fi

      - name: Commit and Push Results
        if: ${{ !env.ACT }}  # Only run if NOT running with act
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the new files
          git add news/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Commit with timestamp
            git commit -m "Add OpenAI news for $(date +%Y-%m-%d) - ${{ matrix.model }}"
          
            # Retry push with rebase up to 5 times
            max_retries=5
            retry_count=0
          
            while [ $retry_count -lt $max_retries ]; do
              echo "Attempting to push (attempt $((retry_count + 1))/$max_retries)..."
          
              if git push; then
                echo "Push successful!"
                break
              else
                echo "Push failed, rebasing and retrying..."
                retry_count=$((retry_count + 1))
          
                if [ $retry_count -lt $max_retries ]; then
                  # Pull with rebase to get latest changes
                  git pull --rebase origin ${{ github.ref_name }}
                  # Wait a random amount of time to reduce conflicts
                  sleep $((RANDOM % 10 + 1))
                else
                  echo "Max retries reached, push failed"
                  exit 1
                fi
              fi
            done
          
            echo "Changes committed and pushed successfully"
          fi
